# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.0
  docker: circleci/docker@2.4.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_and_test: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
  build_and_push_docker_image:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $XROBOTZYH_DOCKERHUB
          password: $XROBOTZYH_PWD_DOCKERHUB
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $XROBOTZYH_DOCKERHUB/openclassrooms:$TAG .
            echo $XROBOTZYH_PWD_DOCKERHUB | docker login -u $XROBOTZYH_DOCKERHUB --password-stdin
            docker push $XROBOTZYH_DOCKERHUB/openclassrooms:$TAG
  deploy:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $XROBOTZYH_DOCKERHUB
          password: $XROBOTZYH_PWD_DOCKERHUB
    steps:
      - checkout
      - run:
          name: deploy to render
          command: |
            deploy_url=$RENDER_DEPLOY_HOOK_URL
            curl deploy_url
# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs: # work only on branch main
      - build_and_test
      - build_and_push_docker_image:
          filters:
            branches:
              only:
                - dev
      - deploy:
          filters:
            branches:
              only:
                - dev