# Generated by Django 3.0 on 2023-11-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20231109_2202'),
    ]

    operations = [
        migrations.DeleteModel('Address'),
        migrations.DeleteModel('Letting'),
        migrations.DeleteModel('Profile'),
    ]
